<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerT2509Gk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT2509Gk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT2509Gk.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerT2509Gk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerT2509Gk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'T2509Gk',
    'container.build_id' => '421be1ce',
    'container.build_time' => 1517215780,
));
