<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\ContainerT2509Gk\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerT2509Gk/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerT2509Gk.legacy');
=======
if (\class_exists(\ContainerU7xfnIE\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU7xfnIE/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerU7xfnIE.legacy');
>>>>>>> daf63ea2b894cb413c1e100943f94d07a4d6e7d4

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\ContainerT2509Gk\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerT2509Gk\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'T2509Gk',
    'container.build_id' => '421be1ce',
    'container.build_time' => 1517215780,
=======
    \class_alias(\ContainerU7xfnIE\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerU7xfnIE\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'U7xfnIE',
    'container.build_id' => 'f6d3bf0a',
    'container.build_time' => 1516957975,
>>>>>>> daf63ea2b894cb413c1e100943f94d07a4d6e7d4
));
